const { motion } = require("framer-motion");
console.log("motion.div:", typeof motion.div);
console.log("motion.span:", typeof motion.span);
console.log("motion.section:", typeof motion.section);
console.log("motion.article:", typeof motion.article);
console.log("motion.nav:", typeof motion.nav);
console.log("motion.header:", typeof motion.header);
console.log("motion.footer:", typeof motion.footer);
console.log("motion.p:", typeof motion.p);
console.log("motion.h1:", typeof motion.h1);
console.log("motion.h2:", typeof motion.h2);
console.log("motion.h3:", typeof motion.h3);
